---
name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Hugo
        run: |
          curl --location --remote-name --silent "https://github.com/gohugoio/hugo/releases/download/v0.82.0/hugo_extended_0.82.0_Linux-64bit.deb"
          sudo apt install --quiet ./hugo_extended_0.82.0_Linux-64bit.deb
          rm -f ./hugo_extended_0.82.0_Linux-64bit.deb
      - name: Build Site
        run: hugo --cleanDestinationDir
      - name: Commit
        run: |
          git config user.email "majordomo@shawnee-skogen.com"
          git config user.name "GitHub Actions"
          git add ./docs
          ( cd themes/hugo-theme-stack && git reset --hard )
          if test -z "$(git status --porcelain)"
          then
            echo "No changes to commit."
            exit 0
          else
            git commit -m "GitHub Action: build"
            git push
          fi
